- lib/about-utils.js
- pages/about/[about].js
- pages/dataset/[datasetid].js
- pages/index.js
This pull request converts server-side rendering to a static page generator. To resolve issue #15
> [SSG][s]: change all getServerSideProp to getStaticProp

- .gitignore
- components/Card.js
- config/config.json
- db/db.js
- db/query.js
- package.json
- pages/_app.js
- pages/index.js
- yarn.lock
> Load data from Github

- package.json
- pages/_app.js
- pages/api/auth/[...nextauth].js
- pages/login.js
- yarn.lock
This pull request adds github login authentication to gift-portal app using `next-auth.js`. How next-auth.js makes authentication easy is explained in #19 . Hence this pull request Closes #19
> Github Login Authentication

- db/db.js
- pages/dataset/[datasetid].js
> [file-preview][m]: Update sample preview in dataset page

- .gitignore
- components/Dashboard.js
- lib/Github.js
- pages/login.js
- styles/pub.css
> Add Dashboard Page

- components/Dashboard.js
- pages/login.js
This is a fix for the last comment mentioned in #42
> Use updated access token

- components/Dashboard.js
- components/Navbar.js
- styles/pub.css
> Update login and logout display

- pages/admin/publisher.js
Fix `LFS Server Key` from the admin page
> [admin] [s] : update giftless-server key from admin

- pages/api/auth/[...nextauth].js
Fix error on try to access login key when logging on github
> [fix] sm] : github session temp key

- .github/workflows/main.yml
- lib/Github.js
- package.json
- pages/admin/publisher.js
- pages/admin/publisher/[id].js
- pages/api/auth/[...nextauth].js
- pages/api/dataset/[id].js
- pages/login.js
> [login] [s] : validate session before display dashboard

- components/Dashboard.js
This pull fixes some issues in #61
> [dashboard][m]: Update datapackage  testing function

- .gitignore
Remove data file from gitignore
> [fix] [s] : remove data folder from gitignore

- lib/Metadata.js
- pages/api/dataset/[id].js
Add again the `POST` and `PUT` API route methods and commented the lfsServer on metastore instance
> [metadata] [m]: undo method commented

- pages/api/auth/[...nextauth].js
This PR fixes user session error when the user tries to log in.
> [fix] [s] : validate session before encrypt

- pages/api/auth/[...nextauth].js
fix user session login on github
> [fix][s]: login validation info

- pages/api/auth/[...nextauth].js
This PR fix login redirect when the user login and logout
> [fix] [s] redirect user login

- components/Dashboard.js
- lib/Metastore.js
- pages/_app.js
- pages/dataset/[datasetid].js
- pages/index.js
This pull updates the MetastoreApollo to Metastore based on the comment in #75
> [Metastore][s]: Update MetastoreApollo to Metastore

- components/Dashboard.js
- lib/utils.js
This pull simply adds the id field to a dataset, as this is used in the publisher.
> [dataset][s]: Add id field to dataset

- pages/api/auth/[...nextauth].js
This PR fixes the redirect when login and logout direct to the `/dashboard` page
> [fix] [s] : redirect login and logout to dashboard

- components/Search.js
- pages/index.js
This pull request fix search operation base on #107
> Fix search

- components/Card.js
* Update icon size to align them.
* Center text vertically next to the icons.
* Remove commented code (which looks like it won't be used at any point since we just accept CSV files).
> [card-component][s]: Set text to 'CSV resources', center text vertically

- components/Card.js
- lib/utils.js
- pages/dataset/[datasetid].js
> [Dataset][m]: Update date display

- components/Card.js
- lib/utils.js
- pages/dataset/[datasetid].js
> [Dataset][m]: Update metadata display

- components/Dashboard.js
- lib/utils.js
- pages/admin/publisher.js
- pages/admin/publisher/edit-metadata/[id].js
- pages/dataset/[datasetid].js
This pull fixes the table preview bug.
> Fix table preview bug

- components/Dashboard.js
- pages/admin/publisher.js
- pages/admin/publisher/edit-metadata/[id].js
> Add "Edit metadata" feature

- package.json
- pages/admin/publisher.js
- pages/admin/publisher/edit-metadata/[id].js
- styles/pub.css
- yarn.lock
> Fix skip to  metadata feature 

- pages/dataset/[datasetid].js
> [WIP] Update metadata display in dataset page

- cypress/integration/pages/home_page/basic_spec.js
- pages/admin/publisher/[id].js
- pages/admin/publisher/edit-metadata/[id].js
This pull request implements datopian/gift-publisher#42 (check login user before viewing publisher)
> Publisher update

- lib/utils.js
This pull updates the fields added to the dataset after processing
> [Utils][m]: Update process metadata to add new fields

- package.json
- yarn.lock
This pull updates metastore-lib-js to latest version
> [metastore-lib][s]: Update metastore-lib to latest version

- lib/utils.js
This pull fixes the schema generation error shown in a datapackage
> [Utils][m]: Fix schema error issue

- lib/utils.js
- package.json
- pages/api/dataset/[id].js
- pages/dataset/[datasetid].js
- yarn.lock
> [Dataset][s]: Update retrieval of sample and schema

- components/Card.js
- lib/Metastore.js
- lib/utils.js
- pages/dataset/[datasetid].js
- pages/index.js
> [dataset][m]: Update dataset image display

- package.json
- yarn.lock
This PR updated the publisher version to the latest
> Update publisher version

- package.json
- styles/pub.css
- yarn.lock
This PR updates giftpub in portal to the latest version.
> [Giftpub][m]: Update publisher version and styles

- components/Navbar.js
- pages/api/auth/[...nextauth].js
- pages/api/dataset/[id].js
> [Auth] Remove pop up github signin

- lib/utils.js
> [Utils][s]: Fix build error

- package.json
- yarn.lock
This PR updates the gift publisher package in portal to the latest version. 
The latest version of gift publisher comes with rich type validation.
> [Giftpub][s]: Update giftpub lib version to latest

- components/Navbar.js
- pages/about.js
- styles/pub.css
@risenW would you mind having a look at this one, please? :slightly_smiling_face:
The goal being to have an About page that's clickable from the navbar, containing some content with footnotes that are also clickable. It looks like it works, but just in case. :grin: 
Thank you!
> [about][m]: Add about page

- pages/dashboard.js
- pages/index.js
This PR fixes #179 
Here, I remove ISR and all new updates are instantly seen.
> [Static Rebuild]: Disable static cache. Fixes #179

- lib/utils.js
- pages/dashboard.js
- pages/index.js
> Filter out os types from repo list

- components/Navbar.js
* Changing the login rectangle to use the tertiary color by default and on hover.
> [navbar][xs]: Update login button to tertiary color

- package.json
- pages/api/dataset/all/[datasetid]/org/[org].js
- pages/dataset/[datasetid].js
- yarn.lock
This PR implement the feature as described here: https://github.com/datopian/gift-publisher/issues/83
> Data merging

- package.json
- pages/api/dataset/all/[datasetid]/org/[org].js
- yarn.lock
this pr enables google credentials to be loaded manually with out .json file. this to make it easy to add credentials to vercel environmental variables.
> Enable Manual configuration

- lib/decret-secret.js
This pr solve this following error `Error on Retrieve Resource: Trying to add data in unsupported state`
> Fix error in decrypting of credentials

- package.json
- yarn.lock
this pr update gift-publisher base on this issue: https://github.com/datopian/gift-publisher/issues/92
> Fix richtype combination and validation

- pages/api/dataset/[id]/datapackage.json.js
- pages/dataset/[datasetid].js
This pr implements datapackage.json download wrt to this issue #20
> DataPackage download

- pages/api/dataset/all/[datasetid]/org/a/[org].js
This pr fix data-merging issue
> Fix data-merging issue

- lib/queries.js
- lib/utils.js
this pr fixes inconsistency in the app query as specified in #207
> Fix inconsistency
